framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        importmap_script_attributes:
            crossorigin: 'anonymous'
            defer: 'defer'
